evaluator_name: Pranav Atreya
institution: Berkeley
logging_server_ip: 34.55.101.123:5000
third_person_camera: right_image
cameras:
  - name: left
    id: 24259877
  - name: right
    id: 24514023
  - name: wrist
    id: 13062452
