evaluator_name: Tony Lee
institution: Stanford
logging_server_ip: 34.55.101.123:5000
third_person_camera: left_image

# Does not use the second external right camera.
cameras:
  - name: left
    id: 25916956
  - name: wrist
    id: 18650758
